# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf1d710e74a47914d18ee7de14c5c332cb864a69df43b69b345ab3e86d38973f67173b0ba35ea294f56132e6433dac36f663d7a4bb48c4acc7e78045c5d9199

test:
  secret_key_base: f460d6c48836c267fcb374fdb8b93c0cccb4275284f7dcf63412b42d8134dd42d3d76ecf5b7ca20b0d11569a7c153bc67d9b51f64718d378f78bd8efa060788e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
